# adopted from https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI
language:android
android:
  components:
    tools # to get the new 'repository-11.xml'
    tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    platform-tools
    build-tools-25.0.2
    android-25
    - extra-android-m2repository

    # Unhash the below line for Google Play Service
    # -extra-google-m2repository
    script:
      - ./gradlew build connectedCheck

    jdk:
      - oraclejdk8 # lamba expression support
